/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rfidabsensiperpus.Gui;
import com.mongodb.client.model.Filters;
import org.bson.conversions.Bson;
import com.mycompany.rfidabsensiperpus.Objects.GenericDAO;
import com.mycompany.rfidabsensiperpus.Objects.Mahasiswa;
import com.mycompany.rfidabsensiperpus.Objects.PetugasPerpus;
import com.mycompany.rfidabsensiperpus.util.EncryptionUtils;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import com.mycompany.rfidabsensiperpus.Utils.SecurityUtils;
/**
 *
 * @author ADVAN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID_anggota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Masuk = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        lblError1 = new javax.swing.JLabel();
        lblError2 = new javax.swing.JLabel();
        lblError3 = new javax.swing.JLabel();
        lblError4 = new javax.swing.JLabel();
        lblError5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setPreferredSize(new java.awt.Dimension(800, 500));
        panel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Library");
        panel1.add(jLabel1);
        jLabel1.setBounds(360, 90, 80, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setText("USERNAME");
        panel1.add(jLabel2);
        jLabel2.setBounds(200, 150, 90, 14);

        ID_anggota.setPreferredSize(new java.awt.Dimension(100, 22));
        ID_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_anggotaActionPerformed(evt);
            }
        });
        ID_anggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ID_anggotaKeyTyped(evt);
            }
        });
        panel1.add(ID_anggota);
        ID_anggota.setBounds(200, 170, 390, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setText("PASSWORD");
        panel1.add(jLabel3);
        jLabel3.setBounds(200, 230, 60, 14);

        Masuk.setBackground(new java.awt.Color(153, 0, 51));
        Masuk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Masuk.setForeground(new java.awt.Color(255, 255, 255));
        Masuk.setText("Masuk");
        Masuk.setPreferredSize(new java.awt.Dimension(100, 22));
        Masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukActionPerformed(evt);
            }
        });
        panel1.add(Masuk);
        Masuk.setBounds(200, 310, 400, 40);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        panel1.add(txtPassword);
        txtPassword.setBounds(200, 250, 390, 30);

        lblError1.setForeground(new java.awt.Color(204, 0, 51));
        panel1.add(lblError1);
        lblError1.setBounds(280, 350, 260, 20);

        lblError2.setForeground(new java.awt.Color(204, 0, 51));
        panel1.add(lblError2);
        lblError2.setBounds(200, 200, 200, 20);

        lblError3.setForeground(new java.awt.Color(204, 0, 51));
        panel1.add(lblError3);
        lblError3.setBounds(200, 280, 200, 20);

        lblError4.setForeground(new java.awt.Color(204, 0, 51));
        panel1.add(lblError4);
        lblError4.setBounds(410, 200, 180, 20);

        lblError5.setForeground(new java.awt.Color(204, 0, 51));
        panel1.add(lblError5);
        lblError5.setBounds(400, 280, 190, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ID_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_anggotaActionPerformed
   
    
    }//GEN-LAST:event_ID_anggotaActionPerformed

    private void ID_anggotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ID_anggotaKeyTyped

                // TODO add your handling code here:
    }//GEN-LAST:event_ID_anggotaKeyTyped

    private void MasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukActionPerformed
        String username = ID_anggota.getText();
        String password = new String(txtPassword.getPassword());
        
        //hapus error lama
        lblError1.setText("");
        lblError2.setText("");
        lblError3.setText("");
        lblError4.setText("");
        lblError1.setText("");
        
        //Validasi jika kosong
        if (username.isEmpty() && password.isEmpty()) {
            lblError1.setText("Username dan password harus diisi!");
            return;
        }
        
        //kalau username kosong
        if (username.isEmpty()) {
            lblError2.setText("Username harus diisi!");
            return;
        }
        
       
        //kalau password kosong
        if (password.isEmpty()) {
            lblError3.setText("Password harus diisi!");
            return;
        }
        
    
        try {
            GenericDAO<PetugasPerpus> dao =
                    new GenericDAO<>("users", PetugasPerpus.class);

            Bson filter = Filters.eq("username", username);

            PetugasPerpus petugas = dao.findOne(filter);

            if (petugas != null &&
                SecurityUtils.getHash(password, SecurityUtils.SHA_256)
                        .equals(petugas.getPassword())) {

                petugas.setLastLogin(LocalDateTime.now());

                dao.update(
                    Filters.eq("username", petugas.getUsername()),
                    petugas
                );

                JOptionPane.showMessageDialog(
                        this,
                        "Login Berhasil, selamat datang "
                        + petugas.getNamaPetugas());

                Dashboard db = new Dashboard();
                db.setVisible(true);

                this.dispose();

            } else {
                lblError5.setText("Username atau password salah!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage());
        }
        
     
    }//GEN-LAST:event_MasukActionPerformed

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
  
               
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.out.println("LOGIN KE JALAN");
        new Login().setVisible(true);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID_anggota;
    private javax.swing.JButton Masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblError2;
    private javax.swing.JLabel lblError3;
    private javax.swing.JLabel lblError4;
    private javax.swing.JLabel lblError5;
    private javax.swing.JPanel panel1;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
